// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABM621Qa6uIp6lNml1eImZJyZ4wKNLzt0',
    appId: '1:1055689077445:web:a6e5dc57fb4eb2bb8f76ac',
    messagingSenderId: '1055689077445',
    projectId: 'new-trial1-370a6',
    authDomain: 'new-trial1-370a6.firebaseapp.com',
    storageBucket: 'new-trial1-370a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMcDV39oGf7lVYM_kCmqFDFKgdRpHNP0',
    appId: '1:1055689077445:android:e2ca3bb86ae0ace28f76ac',
    messagingSenderId: '1055689077445',
    projectId: 'new-trial1-370a6',
    storageBucket: 'new-trial1-370a6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABM621Qa6uIp6lNml1eImZJyZ4wKNLzt0',
    appId: '1:1055689077445:web:8111d27b603a08f58f76ac',
    messagingSenderId: '1055689077445',
    projectId: 'new-trial1-370a6',
    authDomain: 'new-trial1-370a6.firebaseapp.com',
    storageBucket: 'new-trial1-370a6.appspot.com',
  );

}